name:                cabal-build-programs
version:             0.1.0.1
github:              "deech/cabal-build-programs"
license:             BSD3
author:              "Aditya Siram"
maintainer:          "aditya.siram@gmail.com"
copyright:           "Aditya Siram, 2019"

extra-source-files:
- README.org

synopsis:            Adds executable dependencies to the Cabal build
category:            Distribution
description:         Please see the README on GitHub at <https://github.com/deech/cabal-build-programs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - Cabal >= 2.2.0.0 && < 4
